## This notebook classifies the test data given against the model created at the link below:
#### [https://github.com/sweagle07/attack_classification/blob/main/AttackClassifier_train_valid_set.ipynb]

#### **To execute this notebook with new data, update the variable in the cell below to the data to classify file:**
#### test_file_name = 'test'

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time 
import pickle

from sklearn.metrics import classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier

## File name variables to control data/model import and export
## it expects a csv without headers similar to the sample data given

test_file_name = 'test'

In [2]:
train_file_name = 'train_df.pkl'
model_file_name = train_file_name + '_model.sav'

pd.set_option('display.max_columns',None)

### Read test data into data frame and add column headers

In [3]:
test_df = pd.read_csv(test_file_name, names=['duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes', 
                                           'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins', 'logged_in', 
                                           'num_compromised', 'root_shell', 'su_attempted', 'num_root', 'num_file_creations',
                                           'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login', 
                                           'is_guest_login', 'count', 'srv_count', 'serror_rate', 'srv_serror_rate', 
                                           'rerror_rate', 'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate', 
                                           'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count', 'dst_host_same_srv_rate', 
                                           'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate', 
                                           'dst_host_serror_rate', 'dst_host_srv_serror_rate', 'dst_host_rerror_rate', 
                                           'dst_host_srv_rerror_rate','category'])

In [4]:
test_df.shape

(311029, 42)

#### Save off a clean copy of imported test data

In [5]:
test_df_orig = test_df.copy()

#### Take a quick look at test data to see if it's what I am expecting
#### No surprises so far

In [6]:
test_df.head()

duration protocol_type  service flag  src_bytes  dst_bytes  land  \
0         0           udp  private   SF        105        146     0   
1         0           udp  private   SF        105        146     0   
2         0           udp  private   SF        105        146     0   
3         0           udp  private   SF        105        146     0   
4         0           udp  private   SF        105        146     0   

   wrong_fragment  urgent  hot  num_failed_logins  logged_in  num_compromised  \
0               0       0    0                  0          0                0   
1               0       0    0                  0          0                0   
2               0       0    0                  0          0                0   
3               0       0    0                  0          0                0   
4               0       0    0                  0          0                0   

   root_shell  su_attempted  num_root  num_file_creations  num_shells  \
0           0             0         0                   0           0   
1           0             0         0                   0           0   
2           0             0         0                   0           0   
3           0             0         0                   0           0   
4           0             0         0                   0           0   

   num_access_files  num_outbound_cmds  is_host_login  is_guest_login  count  \
0                 0                  0              0               0      1   
1                 0                  0              0               0      1   
2                 0                  0              0               0      1   
3                 0                  0              0               0      2   
4                 0                  0              0               0      2   

   srv_count  serror_rate  srv_serror_rate  rerror_rate  srv_rerror_rate  \
0          1          0.0              0.0          0.0              0.0   
1          1          0.0              0.0          0.0              0.0   
2          1          0.0              0.0          0.0              0.0   
3          2          0.0              0.0          0.0              0.0   
4          2          0.0              0.0          0.0              0.0   

   same_srv_rate  diff_srv_rate  srv_diff_host_rate  dst_host_count  \
0            1.0            0.0                 0.0             255   
1            1.0            0.0                 0.0             255   
2            1.0            0.0                 0.0             255   
3            1.0            0.0                 0.0             255   
4            1.0            0.0                 0.0             255   

   dst_host_srv_count  dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                 254                     1.0                    0.01   
1                 254                     1.0                    0.01   
2                 254                     1.0                    0.01   
3                 254                     1.0                    0.01   
4                 254                     1.0                    0.01   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.00                          0.0   
1                         0.00                          0.0   
2                         0.00                          0.0   
3                         0.00                          0.0   
4                         0.01                          0.0   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                   0.0                       0.0                   0.0   
1                   0.0                       0.0                   0.0   
2                   0.0                       0.0                   0.0   
3                   0.0                       0.0                   0.0   
4                   0.0                       0.0                   0.0   

   dst_host_srv_

In [7]:
test_df.describe()

duration     src_bytes     dst_bytes           land  \
count  311029.000000  3.110290e+05  3.110290e+05  311029.000000   
mean       17.902736  1.731702e+03  7.479937e+02       0.000029   
std       407.644400  1.276567e+05  1.612018e+04       0.005379   
min         0.000000  0.000000e+00  0.000000e+00       0.000000   
25%         0.000000  1.050000e+02  0.000000e+00       0.000000   
50%         0.000000  5.200000e+02  0.000000e+00       0.000000   
75%         0.000000  1.032000e+03  0.000000e+00       0.000000   
max     57715.000000  6.282565e+07  5.203179e+06       1.000000   

       wrong_fragment         urgent            hot  num_failed_logins  \
count   311029.000000  311029.000000  311029.000000      311029.000000   
mean         0.000762       0.000051       0.014677           0.002363   
std          0.040367       0.009821       0.312068           0.049990   
min          0.000000       0.000000       0.000000           0.000000   
25%          0.000000       0.000000       0.000000           0.000000   
50%          0.000000       0.000000       0.000000           0.000000   
75%          0.000000       0.000000       0.000000           0.000000   
max          3.000000       3.000000     101.000000           4.000000   

           logged_in  num_compromised     root_shell   su_attempted  \
count  311029.000000    311029.000000  311029.000000  311029.000000   
mean        0.172476         0.011243       0.000199       0.000023   
std         0.377794         1.958325       0.014117       0.005947   
min         0.000000         0.000000       0.000000       0.000000   
25%         0.000000         0.000000       0.000000       0.000000   
50%         0.000000         0.000000       0.000000       0.000000   
75%         0.000000         0.000000       0.000000       0.000000   
max         1.000000       796.000000       1.000000       2.000000   

            num_root  num_file_creations     num_shells  num_access_files  \
count  311029.000000       311029.000000  311029.000000     311029.000000   
mean        0.008359            0.000958       0.000084          0.000772   
std         2.165196            0.193119       0.012930          0.029453   
min         0.000000            0.000000       0.000000          0.000000   
25%         0.000000            0.000000       0.000000          0.000000   
50%         0.000000            0.000000       0.000000          0.000000   
75%         0.000000            0.000000       0.000000          0.000000   
max       878.000000          100.000000       5.000000          4.000000   

       num_outbound_cmds  is_host_login  is_guest_login          count  \
count           311029.0  311029.000000   311029.000000  311029.000000   
mean                 0.0       0.000039        0.002424     269.247019   
std                  0.0       0.006211        0.049177     219.834412   
min                  0.0       0.000000        0.000000       0.000000   
25%                  0.0       0.000000        0.000000      17.000000   
50%                  0.0       0.000000        0.000000     212.000000   
75%                  0.0       0.000000        0.000000     511.000000   
max                  0.0       1.000000        1.000000     511.000000   

           srv_count    serror_rate  srv_serror_rate    rerror_rate  \
count  311029.000000  311029.000000    311029.000000  311029.000000   
mean      235.580039       0.059215         0.059193       0.142585   
std       239.308028       0.233873         0.234818       0.347564   
min         0.000000       0.000000         0.000000       0.000000   
25%         7.000000       0.000000         0.000000       0.000000   
50%       126.000000       0.000000         0.000000       0.000000   
75%       511.000000       0.000000         0.000000       0.000000   
max       511.000000       1.000000         1.000000       1.000000   

       srv_rerror_rate  same_srv_rate  diff_srv_rate  srv_diff_host_rate  \
count    311029.000000  

In [8]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311029 entries, 0 to 311028
Data columns (total 42 columns):
 #   Column                       Non-Null Count   Dtype  
---  ------                       --------------   -----  
 0   duration                     311029 non-null  int64  
 1   protocol_type                311029 non-null  object 
 2   service                      311029 non-null  object 
 3   flag                         311029 non-null  object 
 4   src_bytes                    311029 non-null  int64  
 5   dst_bytes                    311029 non-null  int64  
 6   land                         311029 non-null  int64  
 7   wrong_fragment               311029 non-null  int64  
 8   urgent                       311029 non-null  int64  
 9   hot                          311029 non-null  int64  
 10  num_failed_logins            311029 non-null  int64  
 11  logged_in                    311029 non-null  int64  
 12  num_compromised              311029 non-null  int64  
 13 

## Perform the same transformation steps as done in modelling phase

### Create overarching groups of attacks and prep data for classification

In [9]:
DOS = ['back.','land.','neptune.','pod.','smurf.','teardrop.']
R2L = ['ftp_write.','guess_passwd.','imap.','multihop.','phf.','spy.','warezclient.','warezmaster.']
U2R = ['buffer_overflow.', 'loadmodule.','perl.','rootkit.']
probing = ['ipsweep.','nmap.','portsweep.','satan.']
normal = 'normal.'

In [10]:
def get_group(x):
    if x in R2L:
        return 4
    elif x in U2R:
        return 3
    elif x in DOS:
        return 2
    elif x in probing:
        return 1
    elif x == normal:
        return 0
    else: return 10

#### Add column with mapping to various Attack Types
#### Attack Type is the target feature for prediction

In [11]:
test_df['attack_type'] = test_df['category'].apply(get_group)

In [12]:
test_df.head()

duration protocol_type  service flag  src_bytes  dst_bytes  land  \
0         0           udp  private   SF        105        146     0   
1         0           udp  private   SF        105        146     0   
2         0           udp  private   SF        105        146     0   
3         0           udp  private   SF        105        146     0   
4         0           udp  private   SF        105        146     0   

   wrong_fragment  urgent  hot  num_failed_logins  logged_in  num_compromised  \
0               0       0    0                  0          0                0   
1               0       0    0                  0          0                0   
2               0       0    0                  0          0                0   
3               0       0    0                  0          0                0   
4               0       0    0                  0          0                0   

   root_shell  su_attempted  num_root  num_file_creations  num_shells  \
0           0             0         0                   0           0   
1           0             0         0                   0           0   
2           0             0         0                   0           0   
3           0             0         0                   0           0   
4           0             0         0                   0           0   

   num_access_files  num_outbound_cmds  is_host_login  is_guest_login  count  \
0                 0                  0              0               0      1   
1                 0                  0              0               0      1   
2                 0                  0              0               0      1   
3                 0                  0              0               0      2   
4                 0                  0              0               0      2   

   srv_count  serror_rate  srv_serror_rate  rerror_rate  srv_rerror_rate  \
0          1          0.0              0.0          0.0              0.0   
1          1          0.0              0.0          0.0              0.0   
2          1          0.0              0.0          0.0              0.0   
3          2          0.0              0.0          0.0              0.0   
4          2          0.0              0.0          0.0              0.0   

   same_srv_rate  diff_srv_rate  srv_diff_host_rate  dst_host_count  \
0            1.0            0.0                 0.0             255   
1            1.0            0.0                 0.0             255   
2            1.0            0.0                 0.0             255   
3            1.0            0.0                 0.0             255   
4            1.0            0.0                 0.0             255   

   dst_host_srv_count  dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                 254                     1.0                    0.01   
1                 254                     1.0                    0.01   
2                 254                     1.0                    0.01   
3                 254                     1.0                    0.01   
4                 254                     1.0                    0.01   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.00                          0.0   
1                         0.00                          0.0   
2                         0.00                          0.0   
3                         0.00                          0.0   
4                         0.01                          0.0   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                   0.0                       0.0                   0.0   
1                   0.0                       0.0                   0.0   
2                   0.0                       0.0                   0.0   
3                   0.0                       0.0                   0.0   
4                   0.0                       0.0                   0.0   

   dst_host_srv_

#### Found that "num_outbound_cmds" is always 0 in train set, also 0s in test data
#### Since it's constant, won't help with prediction,

In [13]:
test_df.num_outbound_cmds.value_counts()

0    311029
Name: num_outbound_cmds, dtype: int64

#### Remove initial columns I removed during model creation

In [14]:
test_df.drop(columns=['category','num_outbound_cmds'], inplace=True)

In [15]:
test_df.shape

(311029, 41)

#### Encode catagorical features 

In [16]:
cat_feats = ['protocol_type','flag','service' ]

In [17]:
test_df_encoded = pd.get_dummies(test_df,columns=cat_feats,drop_first=True)

In [18]:
test_df_encoded.head()

duration  src_bytes  dst_bytes  land  wrong_fragment  urgent  hot  \
0         0        105        146     0               0       0    0   
1         0        105        146     0               0       0    0   
2         0        105        146     0               0       0    0   
3         0        105        146     0               0       0    0   
4         0        105        146     0               0       0    0   

   num_failed_logins  logged_in  num_compromised  root_shell  su_attempted  \
0                  0          0                0           0             0   
1                  0          0                0           0             0   
2                  0          0                0           0             0   
3                  0          0                0           0             0   
4                  0          0                0           0             0   

   num_root  num_file_creations  num_shells  num_access_files  is_host_login  \
0         0                   0           0                 0              0   
1         0                   0           0                 0              0   
2         0                   0           0                 0              0   
3         0                   0           0                 0              0   
4         0                   0           0                 0              0   

   is_guest_login  count  srv_count  serror_rate  srv_serror_rate  \
0               0      1          1          0.0              0.0   
1               0      1          1          0.0              0.0   
2               0      1          1          0.0              0.0   
3               0      2          2          0.0              0.0   
4               0      2          2          0.0              0.0   

   rerror_rate  srv_rerror_rate  same_srv_rate  diff_srv_rate  \
0          0.0              0.0            1.0            0.0   
1          0.0              0.0            1.0            0.0   
2          0.0              0.0            1.0            0.0   
3          0.0              0.0            1.0            0.0   
4          0.0              0.0            1.0            0.0   

   srv_diff_host_rate  dst_host_count  dst_host_srv_count  \
0                 0.0             255                 254   
1                 0.0             255                 254   
2                 0.0             255                 254   
3                 0.0             255                 254   
4                 0.0             255                 254   

   dst_host_same_srv_rate  dst_host_diff_srv_rate  \
0                     1.0                    0.01   
1                     1.0                    0.01   
2                     1.0                    0.01   
3                     1.0                    0.01   
4                     1.0                    0.01   

   dst_host_same_src_port_rate  dst_host_srv_diff_host_rate  \
0                         0.00                          0.0   
1                         0.00                          0.0   
2                         0.00                          0.0   
3                         0.00                          0.0   
4                         0.01                          0.0   

   dst_host_serror_rate  dst_host_srv_serror_rate  dst_host_rerror_rate  \
0                   0.0                       0.0                   0.0   
1                   0.0                       0.0                   0.0   
2                   0.0                       0.0                   0.0   
3                   0.0                       0.0                   0.0   
4                   0.0                       0.0                   0.0   

   dst_host_srv_rerror_rate  attack_type  protocol_type_tcp  \
0                       0.0            0                  0   
1                       0.0            0                  0   
2                       0.0            0                  0   
3                       0.0           10      

In [19]:
test_df_encoded.shape

(311029, 114)

In [20]:
test_df_final = pd.DataFrame(test_df_encoded, columns=['duration', 'src_bytes', 'dst_bytes', 'logged_in', 'count', 'srv_count',
        'same_srv_rate', 'diff_srv_rate', 'srv_diff_host_rate',
        'dst_host_count', 'dst_host_srv_count', 'dst_host_same_srv_rate',
        'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
        'dst_host_srv_diff_host_rate', 'dst_host_srv_serror_rate',
        'protocol_type_tcp', 'protocol_type_udp', 'flag_SF', 'service_ecr_i',
        'service_http','attack_type'])

In [21]:
test_df_final.shape

(311029, 22)

#### Separate data for model fitting

In [22]:
X = test_df_final.drop(['attack_type'],axis=1)
y = test_df_final['attack_type']

### Load in model previously created from training data

In [23]:
model_file_name

'train_df.pkl_model.sav'

In [24]:
i_file = open(model_file_name,'rb')
loaded_model = pickle.load(i_file)
i_file.close()

In [25]:
loaded_model_pred_test = loaded_model.predict(X)

In [26]:
#loaded_model.feature_importances_

## Evaluating the model

#### The model performed a bit worse on the normal and DOS classes
#### normal went from 99% to 83% and DOS from 100% to 82%
#### the probing classification actually improved from a F1 score if 87% to 100%!
#### There is still the same problem with low amount of data for U2R and R2L, so no change there
#### I do see there are new type of attacks that my model also does not recognize (class = 10)

#### **Notes from test/validation run below**
#### The model performed quite well with an F1 score of 99% and 100% for normal and DOS, respecitively
#### it was pretty good at classifying probing attacks with 87% F1 score.
#### The model did not perform well at all for the U2R and R2L attacks. 
#### More data to balance the tree, or perhaps create separate models
normal= 0
probing = 1
DOS = 2
U2R = 3
R2L = 4
unrecognized = 10

In [27]:
print(confusion_matrix(y,loaded_model_pred_test))

[[ 60460     40     93      0      0      0]
 [   251   2082     44      0      0      0]
 [  1211      0 222087      0      0      0]
 [    39      0      0      0      0      0]
 [  5993      0      0      0      0      0]
 [ 17892    594    243      0      0      0]]


In [28]:
print(classification_report(y, loaded_model_pred_test))

/opt/anaconda3/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


              precision    recall  f1-score   support

           0       0.70      1.00      0.83     60593
           1       0.77      0.88      0.82      2377
           2       1.00      0.99      1.00    223298
           3       0.00      0.00      0.00        39
           4       0.00      0.00      0.00      5993
          10       0.00      0.00      0.00     18729

    accuracy                           0.92    311029
   macro avg       0.41      0.48      0.44    311029
weighted avg       0.86      0.92      0.88    311029

